DUSCoreTraining/Pages/Modul03/PageMethode.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DUSCoreTraining.Pages.Modul03
{
    public class PageMethodeModel : PageModel
    {
        public void OnGet()
        {
            var x = Request.Query["id"];
        }
        public void OnGetDrucken([FromRoute] string id)
        {
            //[FromQuery] string id

        }
        //short [FromForm] string id) wie Input name
        public void OnPost([FromForm(Name ="id")] string myId)
        {
          var x=  Request.Form["id"];

        }
    }
}

DUSCoreTraining/Pages/Modul03/TagDemo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DUSCoreTraining.Pages.Modul03
{
    public class TagDemoModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

DUSCoreTraining/Pages/Modul03/calc.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DUSCoreTraining.Pages.Modul03
{
    public class calcModel : PageModel
    {
        public int Ergebnis { get; set; }
        public void OnGet()
        {
          
        }
        public void OnGetAdd([FromQuery]int eins, [FromQuery] int zwei)
        {
            Ergebnis = eins + zwei;
        }

                public void OnGetSub([FromQuery]int eins, [FromQuery] int zwei)
        {
            Ergebnis = eins - zwei;
           
        }
    }

}

DUSCoreTraining/Pages/Modul03/index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DUSCoreTraining.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DUSCoreTraining.Pages.Modul03
{
    public class indexModel : PageModel
    {
        public int Anzahl { get; set; }
        public void OnGet([FromServices] Dumm requestcounter)
        {
            requestcounter.MyProperty++;
            Anzahl = requestcounter.MyProperty;
        }
    }
}

DUSCoreTraining/Pages/Modul03/PageMethode.cshtml
@page "{handler?}/{id?}"
@model DUSCoreTraining.Pages.Modul03.PageMethodeModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PageMethode</title>
</head>
<body>
    <a href="~/Modul03/PageMethode/?handler=drucken&id=12">drucken</a><br />  page <br />
    <a href="~/Modul03/PageMethode/drucken?id=12">drucken</a><br />  page "{handler?} "<br />
    <a href="~/Modul03/PageMethode/drucken/12">drucken</a> page "{handler?}/{id?}"<br />
    <a asp-page="PageMethode" asp-route-handler="drucken" asp-route-id="hannes">taghelper drucken</a><br />
    <a asp-page-handler="drucken" asp-route-id="Sepp" >taghelper drucken</a>


    <br />
    <form method="post" >
        <input name="id" type="text" />
        <button>post </button>

    </form>
</body>
</html>

DUSCoreTraining/Pages/Modul03/RazorPage.cshtml
@page "/hannes2"
@using System.Globalization
@using DUSCoreTraining.Services
@inject Dumm d
@{
    Layout = null;
    var name = "Preishuber-Pflügl";
    var html = "<b>Hannes</b>";
}
@functions 
{
    public Dumm MyProperty { get; set; }
   
    public void OnGet()
    {

    }
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RazorPage</title>
</head>
<body>
    <h1>@DateTime.Now</h1>
    hannesp@ppedv.de
    url als Status

    /kunden/index
    /kunden/edit/123
    /rechnung/Artikel/edit/123
    /rechnung/artikel/index?t=100&s=A
    <hr />
    @name
    @(name + "test")<br />
    <p>@name@name</p><br />
   
    @Html.Raw(html)

    @if (true)
    {
        <br /><text>Hannes</text><br>
        name = "Franz";

    }
    hannes
    @for (int i = 0; i < 12; i++)
    {
        @DateTime.Now.AddMonths(i).ToString("MMMM",new CultureInfo("de-at"));
        <br />
    }
    <br />
    @d.MyProperty

</body>
</html>

DUSCoreTraining/Pages/Modul03/TagDemo.cshtml
@page
@model DUSCoreTraining.Pages.Modul03.TagDemoModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TagDemo</title>
</head>
<body>
    <img src="~/images/maus.jpg" asp-append-version="true"/>
</body>
</html>

DUSCoreTraining/Pages/Modul03/calc.cshtml
@page "{handler?}"
@model DUSCoreTraining.Pages.Modul03.calcModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>calc</title>
</head>
<body>
    <form method="get">
        <input name="eins" />
        <input name="zwei" />
        <button asp-page-handler="Add">+</button>
        <button asp-page-handler="Sub">-</button>

    </form>
    Ergebnis:@Model.Ergebnis


  
</body>
</html>

DUSCoreTraining/Pages/Modul03/index.cshtml
@page
@model DUSCoreTraining.Pages.Modul03.indexModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>index</title>
</head>
<body>
    @Model.Anzahl
</body>
</html>